### ISSUE TITLE
TOML serialising/deserialising stylistic code clean-up

### ISSUE THREAD

**Issue by IVlaD17** [disorderedmaterials/dissolve#1046]
As part of #1039, @trisyoungs raised a couple of issues with the code style being used:
- British spelling (serialise/deserialise) should be used instead of the American (serialize/deserialize)
- Comments explaining the `serialise()` and `deserialise()` methods should be added

While some of those comments will be tackled as part of the PRs that will close #1016 and #1018 there will be some left-over issues that were introduced in the PR that closed #899. Those should get cleaned up as well.

**Comment by rprospero** [comment]
Another vital change that we should make now, before it becomes hard, is to ensure that the `serialise` function is always `const`.  The last thing we need is for the state to be altered when we observe it.

**Comment by IVlaD17** [comment]
> Another vital change that we should make now, before it becomes hard, is to ensure that the `serialise` function is always `const`. The last thing we need is for the state to be altered when we observe it.

Again, I'm not entirely sure how exactly you'd implement this in C/C++, but it might be useful to set-up the C/C++ equivalent of [interfaces](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/interface) for this.

**Comment by rprospero** [comment]
@IVlaD17 C++ has two different ways to implement an interface: multiple inheritance and [concepts](https://en.cppreference.com/w/cpp/language/constraints).  Concepts are nice and could already start cleaning up the template code in my latest PR, but they're not available until C++20.

Honestly, if I take my own bias out of the situation, multiple inheritance could also clean up that template function.  Multiple inheritance can be a disaster if used recklessly, but this is a pretty clear case.  I'll talk it over with Tristan, but that you are probably right about this.

**Comment by rprospero** [comment]
Closed by PY #1052
