### ISSUE TITLE
Reorganise / reinvent AddForcefieldTermsDialog

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#1091]
**Describe the feature / issue**
It's perhaps time to consider reinventing or at least heavily refactoring the `AddForcefieldTermsDialog`.  #971 add the ability for the wizard to display missing atom types when assigning them, and we now also need similar functionality for intramolecular terms.

There are also some nice improvements we can make - principally we could consider automatically attempting to apply the stock of forcefields in the background in order to prune the list down to those which actually successfully describe the target species.

We might also consider adding an option to generate a forcefield from the current geometry - i.e. taking bond distances and angles from the species atom coordinates, and applying a general force constant (or maybe leverage UFF for that part of the work). This would allow "EPSR-style" treatment of more-or-less any system.

**Comment by rprospero** [comment]
I've put together a a prototype replacement for the AddForcefieldTermDialog that uses the new QML GUI from Qt.  If nothing else, the QML has been fantastic for prototyping.

The initial frame is fairly similar to the original, but note that only appropriate force fields are available for selection (the species is benzene).
![20230317_10h53m20s_grim](https://user-images.githubusercontent.com/1728853/225896230-17d20167-202d-47d1-a17b-321ee16ef7c8.png)

We can simultaneously filter by name and species.

![20230317_10h54m20s_grim](https://user-images.githubusercontent.com/1728853/225896236-56f37465-f54f-4748-af01-3407ae538e49.png)

The next page is fairly similar, though I just realised that I need to fix the text wrapping.

![20230317_10h54m27s_grim](https://user-images.githubusercontent.com/1728853/225896238-2bc23188-78da-409a-a9b7-01fa1c010e9e.png)

Previously, the atom type conflicts only appeared as a warning dialog when clicking the next button.  Now it appears prominently in the dialog.

![20230317_10h54m43s_grim](https://user-images.githubusercontent.com/1728853/225896241-1c4dcb5b-d305-4c79-979b-fc7a62b35838.png)

The count on the warning automatically updates when atom types are renamed.


![20230317_10h54m50s_grim](https://user-images.githubusercontent.com/1728853/225896243-f5da4b11-7291-45b2-a6c4-1d83eadb177a.png)

The user is informed when the conflicts have been fixed.  It would be trivial to also disable the `Next` button until the  conflicts are fixed.

![20230317_10h55m08s_grim](https://user-images.githubusercontent.com/1728853/225896245-405e91e8-d45b-4dc2-b149-8ac43b22f85d.png)

Again, fairly similar to the original 

![20230317_10h55m54s_grim](https://user-images.githubusercontent.com/1728853/225896246-40f83fd4-8aa4-4d36-967a-76aa9615d2be.png)

Unfortunate issue here.  We had been using a TreeView here, but QML doesn't support TreeViews until 6.4 and we're on 6.2.

![20230317_10h56m05s_grim](https://user-images.githubusercontent.com/1728853/225896248-6fff0738-0caa-4a9a-b29b-be33084f30e8.png)

**Comment by rprospero** [comment]
Closed by #1363, #1692, and #1754
