### ISSUE TITLE
Tidy Mac Conan handling

### ISSUE THREAD

**Issue by rprospero** [disorderedmaterials/dissolve#1109]
Currently, there's a lot of ugly code in the Mac packaging code for locating the appropriate shared libraries and getting them included in the final app package.  One example of the ugliness is that `jq` is now a build time dependency.

The Windows packaging shows how to use `conan install -g deploy` to get all the shared libraries into a known location.  This would remove the `jq` dependency and the need for multiple custom environment variables

**Comment by trisyoungs** [comment]
Closed by #1146.
