### ISSUE TITLE
'Maximise' button doesn't work (v1.0.0 @47855e8a)

### ISSUE THREAD

**Issue by MartaFalko** [disorderedmaterials/dissolve#1111]
Hello, 
it seems that the 'maximise' button in the top right corner of the Dissolve window doesn't work.

**Operating System:**
on IDAaaS

**Comment by trisyoungs** [comment]
Closing as not reproducible in current version (32e7ea7c853906abeb9d96ab9d14625297036226). Probably this is an effect caused by greedy graphing widgets, preventing the window being maximised in certain situations.
