### ISSUE TITLE
Isotopologue ratios can't use numbers above 1

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#1272]
**Describe the bug**
Editing an isotopologue set (e.g. when specifying species isotopes in the `NeutronSQ` module) does not allow relative numbers greater than 1.0 to be input.  In principle, we allow any numerical ratio to be defined, as this is normalised to 1.0 by the code when using the data anyway.

**Comment by trisyoungs** [comment]
Not sure where the issue is: could be in the `IsotopologueSetKeyword` class itself (src/keywords/isotopologueset.cpp), or the associated widget code (src/gui/keywordwidgets/isotopologuesets_funcs.cpp) or some problem in the user interface (UI) file itself (src/gui/keywordwidgets/isotopologuesets.ui).  Might even be an issue in the basic class (src/classes/isotopologueset.cpp) but needs a bit of trial and testing.

**Comment by Danbr4d** [comment]
![image](https://user-images.githubusercontent.com/115464393/226882630-7a9781ef-d968-45ff-b9a2-ad6f13ed2a5f.png)
Screenshot is from my build so it is working with my local build but just checked on IDaaS and the bug does occur there. Seems like it's an issue specific to IDaaS.
