### ISSUE TITLE
Add infrastructure for backwards compatibility for TOML file format.

### ISSUE THREAD

**Issue by rprospero** [disorderedmaterials/dissolve#1300]
We need the infrastructure to enable backwards compatibility for the file format.

- [ ] Decide on location of version information in the input file
- [ ] Decide on version format
  -  Major, minor, patch is easier to tie to a specific Dissolve and group together
  - An incrementing integer is easier to maintain
- [ ] Create upgrade chain for TOML information

**Comment by trisyoungs** [comment]
See #1076.

**Comment by rprospero** [comment]
Redundant with #1076
