### ISSUE TITLE
Reorganise Viewer source files

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#136]
Class / source file names for Viewer classes should reflect the following heirarchy:

ThisWidget:  Base class extending QOpenGLWidget to show content / data
ThisViewer:  Widget containing ThisWidget and associated controls (e.g. toolbar) for read-only manipulation of the underlying data.
ThisEditor:  Widget containing ThisWidget and associated controls (e.g. toolbar) for read/write manipulation of the underlying data.

**Comment by rprospero** [comment]
Moving to a more Movel/View infrastructure makes this change counter-productive.
