### ISSUE TITLE
Add CMake Presets

### ISSUE THREAD

**Issue by rprospero** [disorderedmaterials/dissolve#1404]
As mentioned at the TSC, we would like cmake presets to simplify configuration for new team members.  We've decided to standardise on using the `build` directory for all builds.  We want the following presets to be available:

- [x] GUI : Build with gui support, plus testing, benchmarks, and debugger info
- [x] GUI-RELEASE : Build with gui support with optimisations
- [ ] MPI : Build with MPI support, plus testing, benchmarks, and debugger info
- [ ] MPI-RELEASE : Build with gui support with optimisations
- [ ] CLI : Build only with command line, plus testing, benchmarks, and debugger info
- [ ] CLI-RELEASE : Build with gui support with optimisations
- [ ] SCARF : Build on SCARF with optimisations

**Comment by trisyoungs** [comment]
I'm going to be awkward here and state that, as a general development process, I build and test in `Release` mode, and only resort to `Debug` builds when I can't easily find the problem and need to invoke the powers of `valgrind`. When you cite "debugger info" above does this suggest a `Debug` build?

**Comment by rprospero** [comment]
That was suggesting that the default setup would be a `Debug` build.  I will separate out the testing from the debug symbols.
