### ISSUE TITLE
Memory effect in the G(r) calculation

### ISSUE THREAD

**Issue by Alfam22** [disorderedmaterials/dissolve#143]
After having had the simulation run for a while, and G(r) converges correctly to 0 at large r:
If I now change the population of the box (e.g. 300-> 600 molecules), regenerate and then continue the simulation, the calculated G(r) will converge to levels above 0, the value scaling with the relative change in population. 
I.e. if i change it to smaller values (e.g. 300-> 100), G(r) now converges to levels below 0.

If i save the configuration and restart dissolve completely, G(r) will converge correctly again.
Similarly, if I "Clear Module Data" after changing the box population G(r) will converge correctly again.

I guess it's an easy fix by clearing the module data, but I thought I'd leave a note here....

------------------
Win7, Dissolve-GUI-0.5.4-cd67b762-Win64

**Comment by trisyoungs** [comment]
Closing as stale / resolved.
