### ISSUE TITLE
CalculateDAngle module 2D map is not normalised to g(r)

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#145]
g(r) in 2D map within the DAngle module don't go to 1.0 (currently the whole map is just normalised to 1.0?)

**Comment by rprospero** [comment]
@trisyoungs started (and probably finished) this on the [normalise-gr](https://github.com/projectdissolve/dissolve/commits/normalise-gr) branch.  I'm going to take over looking at this branch.

(This is largely a reminder to myself from the standup)

**Comment by trisyoungs** [comment]
Closed by #1064.
