### ISSUE TITLE
Reduce significant figures in atom type charges

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#1453]
**Describe the feature / issue**
In an analogous manner to recent work on species charges, the ability to reduce the significant figures on atom type charges themselves would also be highly useful.

**Comment by jws-1** [comment]
Is there a clear menu for this to belong to? Or would it to be better to have a button, above the atom types table (alongside `Duplicate`, for instance)?

**Comment by trisyoungs** [comment]
This is an excellent question. Considering the longer game and expecting more options to be required in the future, adding a button seems like the wrong way to go, as does creating a whole new menu (`Forcefield`) to store one action at present.

Perhaps it could go under the `Simulation` menu for the time being?
