### ISSUE TITLE
Heading font colour too light

### ISSUE THREAD

**Issue by rhinoella** [disorderedmaterials/dissolve#1543]
![image](https://github.com/disorderedmaterials/dissolve/assets/101950441/b948e7e6-ab97-4f3a-903a-f4ec2cb39a5f)
The font colour chosen for these headings is too light and I really struggle to read them.

**Comment by trisyoungs** [comment]
@rhinoella Agreed.  In fact it's just a standard label which has been disabled, but the colour could be better. Perhaps it isn't even necessary to disable it, and normal text in the larger font will look acceptable?

**Comment by trisyoungs** [comment]
Closed by #1556.
