### ISSUE TITLE
Better random number generator

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#227]
**Describe the feature / issue**
Utilise "better than rand()" random number generator.  C++11 provides several built-in RNG - [https://isocpp.org/files/papers/n3551.pdf](https://isocpp.org/files/papers/n3551.pdf)

**Comment by peteroupc** [comment]
I should note that the [random number engines currently available in C++](https://en.cppreference.com/w/cpp/numeric/random) leave a lot to be desired.  For example, `default_random_engine` has undefined quality; `mt19937`, `ranlux24`, and `ranlux48` have a bigger-than-necessary state and are [nontrivial to seed](http://www.pcg-random.org/posts/cpp-seeding-surprises.html); and `minstd_rand0` and `minstd_rand` admit too few seeds.  Although `discard_block_engine` and `shuffle_block_engine` can be used to improve a random engine's quality, it's hard to tell whether the quality is improved this way without [testing](https://github.com/peteroupc/peteroupc.github.io/blob/master/randomtest.md).

There are other considerations as well; see also https://github.com/nest/nest-simulator/issues/1440.

**Comment by trisyoungs** [comment]
https://www.pcg-random.org/
