### ISSUE TITLE
Saving and reopening of simulation not possible

### ISSUE THREAD

**Issue by Alfam22** [disorderedmaterials/dissolve#238]
When I save my simulation, close Dissolve and try to reopen the local simulation *.txt, it cannot successfully open the file.
It gives a warning and then opens an empty simulation.
It is not quite clear to me what causes the behaviour. 
I have observed it for example in the following cases:

A)  1.New simulation
2. I add an Atomtype (e.g. Ga or others) into the Forcefield-Atomtype tab.
3. I enter some L-J Parameters (or also not) and save the file.
4. After closing Dissolve I cannot reopen the file and the error message below:
![grafik](https://user-images.githubusercontent.com/35522548/75441405-88c62280-5955-11ea-8700-16e82319ccd4.png)

================================================================================
*                               Parse Input File                               *
================================================================================

Setting up process pool 'World'...
Process with world rank 0 added to pool 'World' with local rank 0.
There are 1 processes in pool 'World' (max groups = 1).

--> Created Species 'Ga'

Parsing Species 'Ga'
Found end of Site 'Ga'.
Found end of Species 'Ga'.

--> Created Species 'I'

Parsing Species 'I'
Found end of Site 'I'.
Found end of Species 'I'.

Parsing PairPotentials block...
Found end of PairPotentials block.

--> Created Configuration 'NewConfiguration'

Parsing Configuration block 'NewConfiguration'...
Found end of Configuration block.

Executing generator procedure for Configuration 'NewConfiguration'...

[Box] Volume is 1.000000 cubic Angstroms (reciprocal volume = 2.480502e+002)
[Box] Type is Cubic: A = 1.0000e+000 B = 1.0000e+000 C = 1.0000e+000, alpha = 9.0000e+001 beta = 9.0000e+001 gamma = 9.0000e+001
[AddSpecies] Adding species 'Ga' - population is 800.
[AddSpecies] Density for new species is 4.458900 g/cm3.
[AddSpecies] Current Box scaled by 27.489222 - new volume is 2.077243e+004 cubic Angstroms.
[AddSpecies] Positioning type is 'Random' and rotation is on.
[AddSpecies] New Configuration density is 0.038513 atoms/Angstrom3.
[AddSpecies] Adding species 'I' - population is 1200.
[AddSpecies] Density for new species is 4.458900 g/cm3.
[AddSpecies] Current Box scaled by 1.550875 - new volume is 7.748502e+004 cubic Angstroms.
[AddSpecies] Positioning type is 'Random' and rotation is on.
[AddSpecies] New Configuration density is 0.025811 atoms/Angstrom3.

Generating cells for box - minimum cells per side is 3, cell size is 7.000000...
Initial divisions based on cell size are (x,y,z) = (6,6,6)
Shortest side (axis 0) will have cell length of 7.105391 Angstroms.
Accepted cell length of 7.105391 Angstroms (6 divisions) for axis 1, since it was within tolerance (+0.000000e+000).
Accepted cell length of 7.105391 Angstroms (6 divisions) for axis 2, since it was within tolerance (+0.000000e+000).
Final cell partitioning is (x,y,z) = (6,6,6), giving 216 cells in total.
Fractional cell size is (0.166667,0.166667,0.166667).
Constructing array of 216 cells...
Creating cell neighbour lists...
Cell extents required to cover PairPotential range are (x,y,z) = (3,3,3).
Added 151 Cells to representative neighbour list.
Constructing neighbour lists for individual Cells...

--> Created processing layer 'Evolve (Atomic)'

Parsing Layer block 'Evolve (Atomic)'...

Parsing Module block 'AtomShake'...
Found end of Module block.

Parsing Module block 'MD'...
Found end of Module block.

Parsing Module block 'Energy'...
Found end of Module block.
Found end of Layer block.

--> Created processing layer 'RDF / Neutron S(Q)'

Parsing Layer block 'RDF / Neutron S(Q)'...

Parsing Module block 'RDF'...

***  ERROR
***  ERROR     Unrecognised Function type 'Save'.
***  ERROR

***  ERROR
***  ERROR     Failed to parse arguments for Module keyword 'IntraBroadening'.
***  ERROR

***  ERROR
***  ERROR     Errors encountered while parsing input.
***  ERROR

================================================================================
*                              Parse Restart File                              *
================================================================================

Restart file '.restart' does not exist.

================================================================================
*                               Parse Input File                               *
================================================================================

--> Created Species 'Ga'

Parsing Species 'Ga'
Found end of Site 'Ga'.
Found end of Species 'Ga'.

--> Created Species 'I'

Parsing Species 'I'
Found end of Site 'I'.
Found end of Species 'I'.

Parsing PairPotentials block...
Found end of PairPotentials block.

--> Created Configuration 'NewConfiguration'

Parsing Configuration block 'NewConfiguration'...
Found end of Configuration block.

Executing generator procedure for Configuration 'NewConfiguration'...

[Box] Volume is 1.000000 cubic Angstroms (reciprocal volume = 2.480502e+002)
[Box] Type is Cubic: A = 1.0000e+000 B = 1.0000e+000 C = 1.0000e+000, alpha = 9.0000e+001 beta = 9.0000e+001 gamma = 9.0000e+001
[AddSpecies] Adding species 'Ga' - population is 800.
[AddSpecies] Density for new species is 4.458900 g/cm3.
[AddSpecies] Current Box scaled by 27.489222 - new volume is 2.077243e+004 cubic Angstroms.
[AddSpecies] Positioning type is 'Random' and rotation is on.
[AddSpecies] New Configuration density is 0.038513 atoms/Angstrom3.
[AddSpecies] Adding species 'I' - population is 1200.
[AddSpecies] Density for new species is 4.458900 g/cm3.
[AddSpecies] Current Box scaled by 1.550875 - new volume is 7.748502e+004 cubic Angstroms.
[AddSpecies] Positioning type is 'Random' and rotation is on.
[AddSpecies] New Configuration density is 0.025811 atoms/Angstrom3.

Generating cells for box - minimum cells per side is 3, cell size is 7.000000...
Initial divisions based on cell size are (x,y,z) = (6,6,6)
Shortest side (axis 0) will have cell length of 7.105391 Angstroms.
Accepted cell length of 7.105391 Angstroms (6 divisions) for axis 1, since it was within tolerance (+0.000000e+000).
Accepted cell length of 7.105391 Angstroms (6 divisions) for axis 2, since it was within tolerance (+0.000000e+000).
Final cell partitioning is (x,y,z) = (6,6,6), giving 216 cells in total.
Fractional cell size is (0.166667,0.166667,0.166667).
Constructing array of 216 cells...
Creating cell neighbour lists...
Cell extents required to cover PairPotential range are (x,y,z) = (3,3,3).
Added 151 Cells to representative neighbour list.
Constructing neighbour lists for individual Cells...

--> Created processing layer 'Evolve (Atomic)'

Parsing Layer block 'Evolve (Atomic)'...

Parsing Module block 'AtomShake'...
Found end of Module block.

Parsing Module block 'MD'...
Found end of Module block.

Parsing Module block 'Energy'...
Found end of Module block.
Found end of Layer block.

--> Created processing layer 'RDF / Neutron S(Q)'

Parsing Layer block 'RDF / Neutron S(Q)'...

Parsing Module block 'RDF'...

***  ERROR
***  ERROR     Unrecognised Function type 'Save'.
***  ERROR

***  ERROR
***  ERROR     Failed to parse arguments for Module keyword 'IntraBroadening'.
***  ERROR

***  ERROR
***  ERROR     Errors encountered while parsing input.
***  ERROR

================================================================================
*                              Parse Restart File                              *
================================================================================

Restart file '.restart' does not exist.

================================================================================
*                               Parse Input File                               *
================================================================================

--> Created Species 'Ga'

Parsing Species 'Ga'
Found end of Species 'Ga'.

Parsing PairPotentials block...
Found end of PairPotentials block.

Parsing Simulation block...
Random seed set to -1.
Found end of Simulation block.
Finished reading input file.

================================================================================
*                              Parse Restart File                              *
================================================================================

Restart file 'atest.txt.restart' does not exist.

================================================================================
*                               Parse Input File                               *
================================================================================

Parsing PairPotentials block...

***  ERROR
***  ERROR     Unknown AtomType 'Ga' referenced in PairPotentials block.
***  ERROR

***  ERROR
***  ERROR     Errors encountered while parsing input.
***  ERROR

================================================================================
*                              Parse Restart File                              *
================================================================================

Restart file '.restart' does not exist.

[AAu036.txt](https://github.com/projectdissolve/dissolve/files/4261458/AAu036.txt)

**HOWEVER:**
If I additionally create e.g. an atomic species "Ga" and assign the atomtype to be "Ga", 
and then save the file,  I can reopen it without problem.

I have also come across this problem  towards the end of the simulation, I had already accumulated a few thousand cycles for analysis (RDF, Angles). I got the output files and closed dissolve.
I attached the input file.
When I wanted to reopen the txt-file I got a similar error. This time it opened the simulation but all analysis layers were gone.

[AAu036.txt](https://github.com/projectdissolve/dissolve/files/4261458/AAu036.txt)

================================================================================
*                               Parse Input File                               *
================================================================================

Setting up process pool 'World'...
Process with world rank 0 added to pool 'World' with local rank 0.
There are 1 processes in pool 'World' (max groups = 1).

--> Created Species 'Ga'

Parsing Species 'Ga'
Found end of Site 'Ga'.
Found end of Species 'Ga'.

--> Created Species 'I'

Parsing Species 'I'
Found end of Site 'I'.
Found end of Species 'I'.

Parsing PairPotentials block...
Found end of PairPotentials block.

--> Created Configuration 'NewConfiguration'

Parsing Configuration block 'NewConfiguration'...
Found end of Configuration block.

Executing generator procedure for Configuration 'NewConfiguration'...

[Box] Volume is 1.000000 cubic Angstroms (reciprocal volume = 2.480502e+002)
[Box] Type is Cubic: A = 1.0000e+000 B = 1.0000e+000 C = 1.0000e+000, alpha = 9.0000e+001 beta = 9.0000e+001 gamma = 9.0000e+001
[AddSpecies] Adding species 'Ga' - population is 800.
[AddSpecies] Density for new species is 4.458900 g/cm3.
[AddSpecies] Current Box scaled by 27.489222 - new volume is 2.077243e+004 cubic Angstroms.
[AddSpecies] Positioning type is 'Random' and rotation is on.
[AddSpecies] New Configuration density is 0.038513 atoms/Angstrom3.
[AddSpecies] Adding species 'I' - population is 1200.
[AddSpecies] Density for new species is 4.458900 g/cm3.
[AddSpecies] Current Box scaled by 1.550875 - new volume is 7.748502e+004 cubic Angstroms.
[AddSpecies] Positioning type is 'Random' and rotation is on.
[AddSpecies] New Configuration density is 0.025811 atoms/Angstrom3.

Generating cells for box - minimum cells per side is 3, cell size is 7.000000...
Initial divisions based on cell size are (x,y,z) = (6,6,6)
Shortest side (axis 0) will have cell length of 7.105391 Angstroms.
Accepted cell length of 7.105391 Angstroms (6 divisions) for axis 1, since it was within tolerance (+0.000000e+000).
Accepted cell length of 7.105391 Angstroms (6 divisions) for axis 2, since it was within tolerance (+0.000000e+000).
Final cell partitioning is (x,y,z) = (6,6,6), giving 216 cells in total.
Fractional cell size is (0.166667,0.166667,0.166667).
Constructing array of 216 cells...
Creating cell neighbour lists...
Cell extents required to cover PairPotential range are (x,y,z) = (3,3,3).
Added 151 Cells to representative neighbour list.
Constructing neighbour lists for individual Cells...

--> Created processing layer 'Evolve (Atomic)'

Parsing Layer block 'Evolve (Atomic)'...

Parsing Module block 'AtomShake'...
Found end of Module block.

Parsing Module block 'MD'...
Found end of Module block.

Parsing Module block 'Energy'...
Found end of Module block.
Found end of Layer block.

--> Created processing layer 'RDF / Neutron S(Q)'

Parsing Layer block 'RDF / Neutron S(Q)'...

Parsing Module block 'RDF'...

***  ERROR
***  ERROR     Unrecognised Function type 'Save'.
***  ERROR

***  ERROR
***  ERROR     Failed to parse arguments for Module keyword 'IntraBroadening'.
***  ERROR

***  ERROR
***  ERROR     Errors encountered while parsing input.
***  ERROR

================================================================================
*                              Parse Restart File                              *
================================================================================

Restart file '.restart' does not exist.

***  ERROR
***  ERROR     Unrecognised tab ('RDF / Neutron S(Q)') or tab type ('LayerTab') found in state file.
***  ERROR

**Operating System:**
 - OS:  Windows7 64bit
Dissolve-GUI-0.5.6-d3569ec3-Win64

**Comment by trisyoungs** [comment]
There is one usage case, and one bug here:

1) The bug exists in the writing of the PairBroadeningFunction for the IntraBroadening keyword in the RDFModule, which wrongly wrote nothing if no function is chosen.  This has just been fixed in 88f19a7. You can fix your existing input file by removing the IntraBroadening keyword, leaving the remainder of the line ("Save  On") intact.

2) As you have seen, saving an input file containing only atom types breaks Dissolve, as when loading it in again it can't find the atom type named in the PairPotentials block. The reason for this is that atom types are created when reading in the species, and not in the PairPotentials block (where only the parameters are set). I agree that this behaviour can be considered a little odd, and so will address this in upcoming forcefield-related changes.

**Comment by Alfam22** [comment]
Thanks for the help and clarification!--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 27/02/2020, 13:29 Tristan Youngs <notifications@github.com> wrote:

  There is one usage case, and one bug here: 
   
    The bug exists in the writing of the PairBroadeningFunction for the IntraBroadening keyword in the RDFModule, which wrongly wrote nothing if no function is chosen. This has just been fixed in 88f19a7. You can fix your existing input file by removing the IntraBroadening keyword, leaving the remainder of the line ("Save On") intact.  
    As you have seen, saving an input file containing only atom types breaks Dissolve, as when loading it in again it can't find the atom type named in the PairPotentials block. The reason for this is that atom types are created when reading in the species, and not in the PairPotentials block (where only the parameters are set). I agree that this behaviour can be considered a little odd, and so will address this in upcoming forcefield-related changes.

**Comment by Alfam22** [comment]
# Input file written by Dissolve v0.5.6 at 17:02:22 on 03-03-2020.

#------------------------------------------------------------------------------#
#                                   Species                                    #
#------------------------------------------------------------------------------#

Species 'Ga'
  # Atoms
  Atom    1   Ga  0.000000e+000  0.000000e+000  0.000000e+000  'Ga'  0.000000e+000

  # Sites
  Site  'Ga'
    Origin  1
  EndSite
EndSpecies

Species 'I'
  # Atoms
  Atom    1    I  0.000000e+000  0.000000e+000  0.000000e+000  'I'  0.000000e+000

  # Sites
  Site  'I'
    Origin  1
  EndSite
EndSpecies

#------------------------------------------------------------------------------#
#                               Pair Potentials                                #
#------------------------------------------------------------------------------#

PairPotentials
  # Atom Type Parameters
  Parameters  Ga  3.000000e-002  LJ  2.000000e+000  1.800000e+000  0.000000e+000  0.000000e+000
  Parameters  I  -2.000000e-002  LJ  1.500000e+000  2.700000e+000  0.000000e+000  0.000000e+000
  Range  15.000000
  Delta  0.005000
  IncludeCoulomb  True
  CoulombTruncation  Shifted
  ShortRangeTruncation  Shifted
EndPairPotentials

#------------------------------------------------------------------------------#
#                                Configurations                                #
#------------------------------------------------------------------------------#

Configuration  'NewConfiguration'

  # Modules
  Generator
    Parameters
      Real  rho  4.458900e+000
    EndParameters
    Box
      Lengths  1.000000e+000  1.000000e+000  1.000000e+000
      Angles  9.000000e+001  9.000000e+001  9.000000e+001
      NonPeriodic  False
    EndBox
    AddSpecies
      Species  'Ga'
      Population  '800'
      ScaleBox  True
      Density  'rho'  g/cm3
      Rotate  True
      Positioning  Random
    EndAddSpecies
    AddSpecies
      Species  'I'
      Population  '1200'
      ScaleBox  True
      Density  'rho'  g/cm3
      Rotate  True
      Positioning  Random
    EndAddSpecies
  EndGenerator

  Temperature  300.000000

  # Modules
  # -- None
EndConfiguration

#------------------------------------------------------------------------------#
#                              Processing Layers                               #
#------------------------------------------------------------------------------#

Layer  'Evolve (Atomic)'
  Frequency  1

  Module  AtomShake  'AtomShake01'
    Frequency  1

    Configuration  'NewConfiguration'
    StepSize  4.76216e-001
  EndModule

  Module  MD  'MD01'
    Frequency  5

    Configuration  'NewConfiguration'
  EndModule

  Module  Energy  'Energy01'
    Frequency  1

    Configuration  'NewConfiguration'
  EndModule
EndLayer

Layer  'RDF / Neutron S(Q)'
  Frequency  5

  Module  RDF  'RDF01'
    Frequency  1

    Configuration  'NewConfiguration'
    Save  True
  EndModule

  Module  NeutronSQ  'NeutronSQ01'
    Frequency  1

    Configuration  'NewConfiguration'
    QBroadening  'OmegaDependentGaussian'  0.030000
    Reference  mint  'GEM90111.mint01'
    EndReference
  EndModule
EndLayer

Layer  'Refine (EPSR)'
  Frequency  5

  Module  EPSR  'EPSR01'
    Frequency  1
    EReq  2.00000e+002
    Target  'NeutronSQ01'  'Default'
  EndModule
EndLayer

Layer  'Analyse RDF/CN Ga-I'
  Frequency  1

  Module  CalculateRDF  'CalculateRDF01-Ga-I'
    Frequency  1

    Configuration  'NewConfiguration'
    DistanceRange  0.000000e+000  1.500000e+001  5.000000e-002
    SiteA  'Ga'  'Ga'
    SiteB  'I'  'I'
    ExcludeSameMolecule  True
    Save  True
  EndModule

  Module  CalculateCN  'CalculateCN01'
    Frequency  1
    SourceRDF  'CalculateRDF01-Ga-I'
  EndModule
EndLayer

Layer  'Analyse RDF/CN1 I-Ga'
  Frequency  1

  Module  CalculateRDF  'CalculateRDF02-I-Ga'
    Frequency  1

    Configuration  'NewConfiguration'
    DistanceRange  0.000000e+000  1.500000e+001  5.000000e-002
    SiteA  'I'  'I'
    SiteB  'Ga'  'Ga'
    ExcludeSameMolecule  True
    Save  True
  EndModule

  Module  CalculateCN  'CalculateCN02'
    Frequency  1
    SourceRDF  'CalculateRDF02-I-Ga'
  EndModule
EndLayer

Layer  'Analyse RDF/CN Ga-Ga'
  Frequency  1

  Module  CalculateRDF  'CalculateRDF01-Ga-Ga'
    Frequency  1

    Configuration  'NewConfiguration'
    DistanceRange  0.000000e+000  1.500000e+001  5.000000e-002
    SiteA  'Ga'  'Ga'
    SiteB  'Ga'  'Ga'
    ExcludeSameMolecule  True
    Save  True
  EndModule

  Module  CalculateCN  'CalculateCN03'
    Frequency  1
    SourceRDF  'CalculateRDF01-Ga-Ga'
  EndModule
EndLayer

Layer  'Analyse RDF/CN'
  Frequency  1

  Module  CalculateRDF  'CalculateRDF01-I-I'
    Frequency  1

    Configuration  'NewConfiguration'
    DistanceRange  0.000000e+000  1.500000e+001  5.000000e-002
    SiteA  'I'  'I'
    SiteB  'I'  'I'
    ExcludeSameMolecule  True
    Save  True
  EndModule

  Module  CalculateCN  'CalculateCN04'
    Frequency  1
    SourceRDF  'CalculateRDF01-I-I'
  EndModule
EndLayer

Layer  'CalcAngle'
  Frequency  1

  Module  CalculateAngle  'CalculateAngle01(I-Ga)-I'
    Frequency  1

    Configuration  'NewConfiguration'
    RangeAB  2.000000e+000  3.000000e+000  5.000000e-002
    RangeBC  2.000000e+000  3.000000e+000  5.000000e-002
    SiteA  'I'  'I'
    SiteB  'Ga'  'Ga'
    SiteC  'I'  'I'
    ExcludeSameSiteAC  True
    SaveAB  True
    SaveBC  True
    SaveAngle  True
    SaveDAngleAB  True
    SaveDAngleBC  True
  EndModule

  Module  CalculateAngle  'CalculateAngle01(Ga-I)-Ga'
    Frequency  1

    Configuration  'NewConfiguration'
    RangeAB  2.000000e+000  3.000000e+000  5.000000e-002
    RangeBC  2.000000e+000  3.000000e+000  5.000000e-002
    AngleRange  0.000000e+000  1.800000e+002  1.000000e+000
    SiteA  'Ga'  'Ga'
    SiteB  'I'  'I'
    SiteC  'Ga'  'Ga'
    ExcludeSameSiteAC  True
    SaveAB  True
    SaveBC  True
    SaveAngle  True
    SaveDAngleAB  True
    SaveDAngleBC  True
  EndModule

  Module  CalculateAngle  'CalculateAngle01'
    Frequency  1

    Configuration  'NewConfiguration'
    RangeAB  2.000000e+000  1.000000e+001  1.000000e-001
    RangeBC  2.000000e+000  1.000000e+001  1.000000e-001
    AngleRange  0.000000e+000  1.800000e+002  2.000000e+000
    SiteA  'I'  'I'
    SiteB  'Ga'  'Ga'
    SiteC  'I'  'I'
    ExcludeSameSiteAC  True
    SaveAB  True
    SaveBC  True
    SaveAngle  True
    SaveDAngleAB  True
    SaveDAngleBC  True
  EndModule
EndLayer

#------------------------------------------------------------------------------#
#                                  Simulation                                  #
#------------------------------------------------------------------------------#

Simulation
  Seed  -1
EndSimulation

**Comment by trisyoungs** [comment]
That input file loads correctly for me (if I comment out the Reference data, which I don't have).

Are you getting further error messages?

**Comment by Alfam22** [comment]
I didn't get any error messages, as the program just froze.

 

However, I was able to open it now. It seemed my file was "AAu036_glass30C.txt" and the restart file was "AAu036_glass30C.txt.restart".

Once I renamed it to "AAu036_glass30C.restart" I could open it.

 

However, the configuration seems to be always random when I reopen an old simulation.

I.e. the refinement had nicely reproduced my F(Q), then I saved, it and now on the next day, when I open it at say "Run", it starts again from a random arrangement of atoms in the box.

I'm not quite sure how to properly use the created restart points. Do I need to import them somehow?

 

Cheers, Alfred

 

 
 

Gesendet: Freitag, 06. März 2020 um 09:04 Uhr
Von: "Tristan Youngs" <notifications@github.com>
An: projectdissolve/dissolve <dissolve@noreply.github.com>
Cc: Alfam22 <chunkylover89@gmx-topmail.de>, Author <author@noreply.github.com>
Betreff: Re: [projectdissolve/dissolve] Saving and reopening of simulation not possible (#238)


That input file loads correctly for me (if I comment out the Reference data, which I don't have).

Are you getting further error messages?

**Comment by trisyoungs** [comment]
The restart file contains the latest coordinates, amongst a host of other data - renaming the file as you did would have meant that Dissolve would not find / load it (it always assumes it is named after the input file, with the suffix ".restart") so this points to an issue with the restart file itself.

If the restart file is small (or could be zipped up) and email to me then I can take a look. Otherwise, Dropbox or other file sharing will work.

**Comment by Alfam22** [comment]
This time it worked to open the file. So sometimes I can open it and sometimes it freezes, maybe because of the size of the restart file (700 MB) ?

I'll keep on working and try to see if I notice some pattern to this behaviour.

 

Cheers

 
 

Gesendet: Freitag, 06. März 2020 um 12:40 Uhr
Von: "Tristan Youngs" <notifications@github.com>
An: projectdissolve/dissolve <dissolve@noreply.github.com>
Cc: Alfam22 <chunkylover89@gmx-topmail.de>, Author <author@noreply.github.com>
Betreff: Re: [projectdissolve/dissolve] Saving and reopening of simulation not possible (#238)


The restart file contains the latest coordinates, amongst a host of other data - renaming the file as you did would have meant that Dissolve would not find / load it (it always assumes it is named after the input file, with the suffix ".restart") so this points to an issue with the restart file itself.

If the restart file is small (or could be zipped up) and email to me then I can take a look. Otherwise, Dropbox or other file sharing will work.

**Comment by Alfam22** [comment]
Dear Tristan,

 

in the Forcefield-Atom types tab I can choose also a "Lennard-Jones geometric" potential.

Which expression does this refer to? And what are the parameters 3 & 4?

 

Thanks a lot!

Alfred

 
 

Gesendet: Freitag, 06. März 2020 um 12:40 Uhr
Von: "Tristan Youngs" <notifications@github.com>
An: projectdissolve/dissolve <dissolve@noreply.github.com>
Cc: Alfam22 <chunkylover89@gmx-topmail.de>, Author <author@noreply.github.com>
Betreff: Re: [projectdissolve/dissolve] Saving and reopening of simulation not possible (#238)


The restart file contains the latest coordinates, amongst a host of other data - renaming the file as you did would have meant that Dissolve would not find / load it (it always assumes it is named after the input file, with the suffix ".restart") so this points to an issue with the restart file itself.

If the restart file is small (or could be zipped up) and email to me then I can take a look. Otherwise, Dropbox or other file sharing will work.

**Comment by trisyoungs** [comment]
Same form as the Lennard-Jones potential, but using the geometric mean combination rule for both sigma and epsilon (as opposed to just epsilon in the standard form). Parameters 3 and 4 are unused for both LJ forms.

**Comment by trisyoungs** [comment]
Closing (stale).
