### ISSUE TITLE
Move away from Raw Pointers

### ISSUE THREAD

**Issue by rprospero** [disorderedmaterials/dissolve#244]
Currently, the code base uses a large number of raw pointers, which brings a host of problems

* Memory safety cannot be guaranteed by the compiler.  We might attempt to access freed pointers or leak memory.  Diligent programmers can avoid this, but it's better to have this work performed by the compiler
* It slows down onboarding new team members.  Any given pointer could either be an owning pointer or merely an observing pointer and the difference is not immediately clear.

We would prefer to move onto either smart pointers or references, if possible.

This will be a fairly sweeping change through the code base, so care must be taken.  It will also likely be heavily intertwined with the move to standard containers, since many of these pointers are currently managed by the custom containers.

**Comment by rprospero** [comment]
One place that becomes a problem with moving onto purely references is that there are many places where the classes would introduce reference cycles.  For example, the Atom class currently has a [pointer](https://github.com/projectdissolve/dissolve/blob/459f6dcba8ab092ebb0bf32257afae5429ec6cc1/src/classes/molecule.h#L61) to the molecule that contains it, while the Molecule class has an [array of pointers](https://github.com/projectdissolve/dissolve/blob/459f6dcba8ab092ebb0bf32257afae5429ec6cc1/src/classes/molecule.h#L61) to each atom it contains.

This becomes an issue because, unlike pointers, references must be set in the constructor and cannot be changed.  So the Molecule must be passed into the constructor for the Atom, but that Atom's constructor required the reference to the Molecule.  It might be possible to tie the knot by creating one child object inside the constructor of the parent, but it will require careful though.  This is compounded by the fact that the Configuration class maintains a master array of all of the atoms and molecules, which must also be populated with references.

It's possible that using std::reference_wrapper might enable us to avoid some of these issues, but it also may be an indication that smart pointers might be the more intuitive solution for some of these issues.

**Comment by trisyoungs** [comment]
A further potential complication is that the workflow discussed at the previous TSC assumed adherence to a basic [Create Data] -> [Run Simulation on Data] -> [Analyse Data] but there are other use cases where the simulation could actively modify the data (creating / deleting molecules would be a prime example).

Adam is probably correct that at least some smart pointers will have to be used.

**Comment by LamarMoore** [comment]
Instead of explicitly deleting memory you can overwrite it and (for example) resize a vector to either enlarge or shrink. In the short term maybe using smart pointers is the best strategy? Would be interested to see that PR as it may allow me to get more insight into what is happening with the memory.

**Comment by LamarMoore** [comment]
@trisyoungs It may be worth you making the call when you want to formalise these maintenance tasks so you do not lose focus on what/when you are meant to deliver to the user community.

**Comment by rprospero** [comment]
Most of the raw pointers have been dealt with in the move to standard STL classes.  The remaining pointers are often observing pointers.  Keeping this as a separate issue is not necessary.
