### ISSUE TITLE
Issue with CalculateAxisAngle Module vs ARDF of dlputils

### ISSUE THREAD

**Issue by calum-green** [disorderedmaterials/dissolve#397]
**Describe the bug**
Issue with the calculateaxisangle module that is not consistent with the same analysis done using dlputils->ardf. It shows there is no angular dependence upon the rdf unlike ardf. Possibly include a feature that normalises g(r,theta)->1 for long r given any data generated through calculateaxisangle as the data still had to be normalised -> 1 at long r using ardf.

**To Reproduce**
Steps to reproduce the behaviour (if necessary):
1. Run analysis of a refined system using the calculateaxisangle module enabled for good amount of steps
2. Save trajectory file of sim too
3. Compare output of ardf module using trajectory file from dissolve in dlputils with that of calculateaxisangle module and see no change w.r.t angle for g(r,theta)

**Expected behaviour**
Expect angular dependence of rdf to be consistent with ardf in dlputils - angular dependence is shown in Screenshot 2 (dlputils), but not SS 1 (dissolve)

**Screenshots**
<img width="960" alt="CAA1" src="https://user-images.githubusercontent.com/70141032/95558662-81e4af80-0a0e-11eb-9418-06271219c677.png">
<img width="478" alt="CAA2" src="https://user-images.githubusercontent.com/70141032/95558665-827d4600-0a0e-11eb-8a08-37e8b29cc2e0.png">

**Operating System:**
 - OS:  Windows  10

**Comment by rprospero** [comment]
I'm afraid that I'm having trouble reproducing this problem.  Specifically, I've loaded the benzene example and allowed it to run for 2600 iterations. At the end of this, Calculate Axis Angle is showing a clear angular dependence to the RDF.
![2020-11-02-164743_1920x1080_scrot](https://user-images.githubusercontent.com/1728853/97895592-e48a4c00-1d2b-11eb-97f0-35118a767999.png)

Would it be possible to have an example set of files that are producing the issue?

**Comment by trisyoungs** [comment]
Closed by #1064.
