### ISSUE TITLE
Crash of the GUI when Trying to Add Species without forcefield assignments to a mix

### ISSUE THREAD

**Issue by johannabusch** [disorderedmaterials/dissolve#434]
The GUI crashes when the user tries to create a mix of species with one species without forcefield terms with the following error message in the terminal:
![image](https://user-images.githubusercontent.com/56266543/98530673-8acfd780-227f-11eb-9192-14d23e5885f5.png)

If that's supposed to be like that, please ignore this bug report. However, it might be good for the user if there is another error message.

**Comment by trisyoungs** [comment]
Closing (stale/fixed).
