### ISSUE TITLE
Glycine/Mg/ClO4 Forcefields

### ISSUE THREAD

**Issue by HLaurent884** [disorderedmaterials/dissolve#445]
Hi Tris,

Would you be able to add the glycine and Mg(ClO4)2 potentials please.

Glycine: https://doi.org/10.1021/jp108642r
Mg: https://doi.org/10.1021/jp909132a
ClO4: https://doi.org/10.1021/acs.jctc.7b00520

Thanks so much!

Harry

**Comment by rprospero** [comment]
Dissolve now supports importing custom force fields, so users no longer need to wait on the dev team to implement specific ones.
