### ISSUE TITLE
Remove GenericItem classes

### ISSUE THREAD

**Issue by rprospero** [disorderedmaterials/dissolve#453]
Currently, there is a GenericItem class template that handles many aspects needed for multiple data types (e.g. broadcasting, RTTI, serialisation).  However, it has multiple problems to it

1) It's something of a god class that handles multiple independent bits of functionality whose only commonality is that they're needed everywhere
2) It assumes that instances that are containers are full of instances that are also members of GenericItem.  This can be an issue for base types or classes that cannot be extended
3) All functionality must be defined for all classes, even if only parts of it are needed.
4) There is significant boilerplate.

It might be better to reorganize the class as a series of templated functions.  Template specialisation would allow the function to be defined for each type, even if it is not a class and without requiring an inheritance hierarchy.  It would also allow only defining implementations for the classes that need them.

**Comment by trisyoungs** [comment]
I'm currently changing a few bits and pieces here as a result of some work which led to something else, which led here ("Inception", anyone?)

I agree that the inheritance hierarchy is a bit of mess, but one of the main goals of the `GenericItem` class was to have the ability to store a heterogeneous list of various data that gets created and accumulated throughout the simulation. Some minimal inheritance at least is required to achieve that, although if you have a brilliant workaround I'm definitely listening!

**Comment by rprospero** [comment]
I'm thinking that we can get around the inheritance.  As I've been going through this, it looks like all we need is a `std::map<std::string, std::any>`.  This gives us the connection between the name and the value and the call site can use `std::any_cast` to get the correct type from the `std::any`.  As for more generic functions like `broadcast` and `equality`, they can use `std::visit` to handle the different types.
