### ISSUE TITLE
Syntax error: token recognition error at: '\{sum'

### ISSUE THREAD

**Issue by calum-green** [disorderedmaterials/dissolve#512]
**Describe the bug**
When clicking the reset view button (indicated in image) an error is shown in the command line output at the bottom and a slightly odd view of the graph is shown within the EPSR module for the value of the EReq in the R-Fac tab

**Screenshots**
![EReqGraphIssue](https://user-images.githubusercontent.com/70141032/104165487-55677780-53f1-11eb-8a53-6bd83e9d06d8.png)

**Operating System:**
 - OS:  Windows 
 - OS version / flavour:  Windows 10

**Comment by trisyoungs** [comment]
Fixed in #513.
