### ISSUE TITLE
g(r) in restart file

### ISSUE THREAD

**Issue by HLaurent884** [disorderedmaterials/dissolve#531]
Hi Tris,

I hope you are well. We have been looking at the .restart file to try and plot some of the data in external programs (Origin etc). and we are just trying to check which g(r) data shown corresponds to the overall average, a.k.a. the smoothest possible dataset.  By plotting them all out we think that the Original - unbound data is the smoothest and therefore most likely to be the overall average.  Are we correct in thinking this, or is it one of the other listed g(r)s?

All the best,

Harry

**Comment by trisyoungs** [comment]
Extracting data from the restart file is certainly possible, but you may be better off using the `Save` keyword in the `RDFModule` (see https://projectdissolve.com/docs/modules/correlation/rdf/). The files written out using that option give you the bound (i.e. intramolecular), unbound (i.e. intermolecular) and total functions for each partial, as well as the total G(r).

The default averaging size for the g(r) as calculated by the `RDFModule` is 5 - you'll see in the restart file that there are various sets of data labelled `_Avg` which are the historical g(r) data used to form the average.

One other point - questions related to using the code are better off in the forum at https://forum.projectdissolve.com/. GitHub Issues are most effectively used for bug reports etc.
