### ISSUE TITLE
'Input file failed to load' error

### ISSUE THREAD

**Issue by ALad98** [disorderedmaterials/dissolve#534]
When I open a file on dissolve, I get an error message saying that 'the input file failed to load correctly'. The error message I get after this is that the restart file doesn't exist. When this happens most of the simulation goes missing, this error now also appears on previous files that I have worked on last year. I am not sure why they suddenly have this error when they have worked previously and nothing has been changed within the file.    

![image](https://user-images.githubusercontent.com/78853944/107527030-5afedb80-6bb0-11eb-9196-1855a8d4fc85.png)

the error:

***  ERROR
***  ERROR Error setting SpeciesSite - no such site named '' exists in Species 'glycine '.
***  ERROR

***  ERROR
***  ERROR Failed to parse arguments for Module keyword 'Site'.
***  ERROR

***  ERROR
***  ERROR Errors encountered while parsing input.
***  ERROR

================================================================================
*                              Parse Restart File                              *
================================================================================

Restart file '.restart' does not exist.

 - OS:  Windows 
 - OS version / flavour: Windows 10

**Comment by trisyoungs** [comment]
The missing restart file issue is actually another small bug, in that it shouldn't attempt to read the restart file if the input file fails to load. However, this shouldn't itself result in bad reading of the input file. I would need to see the input file so I can see if there's anything obvious and try it out to reproduce the error.

Can you post the full input file here or, if you prefer, email it to me?
