### ISSUE TITLE
Implement UFF-MOF Forcefield

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#561]
**Describe the feature / issue**
Extend, derive from, or otherwise enhance the present UFF implementation to be capable of simulating MOFs.

**Additional details**
Paper can be found here: https://pubs.acs.org/doi/abs/10.1021/ct400952t

**Comment by alinelena** [comment]
not uff better moff-ff


---Dr Alin Marin Elenahttp://alin.elena.space

 ---- On Mon, 01 Mar 2021 10:20:15 +0000 Tristan Youngs <notifications@github.com> wrote ----

**Comment by trisyoungs** [comment]
I'm sure there a lots of "better" forcefields for MOFs out there, but UFF-MOF is readily available in the open literature, and is a relatively simple extension of the original (implemented) UFF. Having to register an account to get a set of parameters is not something I want to get into, given possible licensing issues (Dissolve is open source, after all).

**Comment by alinelena** [comment]
do not get fouled thinking that if you register will get the params.





---Dr Alin Marin Elenahttp://alin.elena.space

 ---- On Tue, 02 Mar 2021 18:33:37 +0000 Tristan Youngs <notifications@github.com> wrote ----
