### ISSUE TITLE
Crash when adding FF terms on GUI

### ISSUE THREAD

**Issue by tfheaden** [disorderedmaterials/dissolve#595]
**Describe the bug**
Crash when adding FF terms on GUI

**To Reproduce**
Steps to reproduce the behaviour (if necessary):
1. Molecule
2. Click "add forcefield terms"
3. Click next on all steps.
4. At last step GUI craches when click on "Finish"
I've tried this on Ethers, and on just water going back to the main devel version (without my ether bits)

 - OS:    Linux  (delete as appropriate)
 - OS version / flavour:  [Ubuntu 18.04

**Comment by trisyoungs** [comment]
Confirmed on 0.8.0 at fb4266a2fc54439dc857a1a9721749fbc6dcd437.
