### ISSUE TITLE
Cannot see molecule when drawing it

### ISSUE THREAD

**Issue by tfheaden** [disorderedmaterials/dissolve#601]
**Describe the bug**
When using "Species > Create > Draw" I select the "pen" then go to draw a molecule, nothing appears in the window. However something is registered as "All C2" appears bottom right if I click and drag (for example). SO my guess is it's just not displaying. If I click OK at that point nothing will display in the "View/Generate", but bottom right will display the number of atoms "All C2" for example. [NOTE: I thought this was on a completely clean version, but he code does include my update of opls/intramolecular.ccp, but didn't think that should effect display behavior, however if bug is not repeatable let me know.]

**Operating System:**
 - OS:    Linux  (delete as appropriate)
 - OS version / flavour:  Ubuntu 18.04 [e.g. Windows 10, Catalina, Ubuntu 18.04]

**Comment by trisyoungs** [comment]
Confirmed independently by another user.
