### ISSUE TITLE
GUI crahses after adding forcefield terms wizard

### ISSUE THREAD

**Issue by tfheaden** [disorderedmaterials/dissolve#607]
**Describe the bug**
GUI crahses after adding forcefield terms wizard (or on occasion has just hung). Works fine for water and ethane, but crashes or hang for anything more complicated (e.g. propane, run as a test). Goes through the wizard fine and seems to correctly work out the intramolecular terms, but crashes when click Finish (or similar - can't remember exact word.

**Operating System:**
 - OS:  Linux  (delete as appropriate)
 - OS version / flavour: Ubuntu 18.04 [e.g. Windows 10, Catalina, Ubuntu 18.04]

**Comment by trisyoungs** [comment]
This looks to be fixed in the latest versions.  @tfheaden can you confirm so the issue can be closed?
