### ISSUE TITLE
Overview Tab

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#644]
**Describe the feature / issue**
Consider implementing an "Overview" tab, first in the list, which displays a block-diagram of all major elements of the simulation, and gives an overview of number / count etc., and provides access into those tabs quickly by double-clicking.

Overview of modules within layers would be particularly useful, and can display frequency info (e.g. highlighted / change of colour if the module will run this iteration). When more complex workflows are implemented via control layers (#88) this kind of overview will be almost a necessity.

**Comment by jws-1** [comment]
Closing as superseded by #1652.
