### ISSUE TITLE
Move to Qt6

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#704]
Planning ahead of moving to Qt6. Specifically, we need to move to 6.1 as QtChart was not introduced until then.

### Primary
- [x] Installables for key platforms
  - [x] Windows 
  - [x] OSX (available via `brew`)
  - [x] Ubuntu 20.04
  - [x] OpenSuSE 15.2 (available via `KDE:Qt6` repo)

### Secondary
- [ ] Compilation on IDAaaS

## Main
- [x] Attempt port of existing code from Qt5 to Qt6.

**Comment by rprospero** [comment]
We're on Qt6
