### ISSUE TITLE
Q atoms

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#72]
Reproduce 'Q' atoms to offer consistency with EPSR. How can they be introduced consistently with the code (AtomTypeList etc.)

Or, don't - how often are they used?  Would potential gradients / geometries be more useful? For instance, a defined cylindrical gradient could be used to reproduce the formation of cylindrical pores in MCM-41.

**Comment by jws-1** [comment]
Closed by #1473 & #1476.
