### ISSUE TITLE
(Sub)Menu item text is elided (Qt6)

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#774]
**Describe the bug**
Menu item text (in submenus?) is elided without reason.

**To Reproduce**
Open menu->submenu and observe that the longest-named item is elided.

**Expected behaviour**
Text should not be elided!

**Screenshots**
![image](https://user-images.githubusercontent.com/11457350/128867318-05af93e4-c0c6-4365-8ea2-fd67d8cafc6e.png)
![image](https://user-images.githubusercontent.com/11457350/128867333-bf0b8957-cec3-44a3-9e56-a27dd5812628.png)

**Operating System:**
 - OS:  Linux
 - OS version / flavour:  OpenSuSE LEAP 15.2

**Comment by rprospero** [comment]
Is this issue still present?  The screenshot below shows the full text in the menus.

![20211130_14h29m25s_grim](https://user-images.githubusercontent.com/1728853/144066056-434d6fcb-d78a-4864-ad8a-ba180f6dc9a0.png)

**Comment by trisyoungs** [comment]
Interesting. The elided text still occurs for me on my system with Gnome, so it might be desktop-specific?

Either way, I searched on this last week and didn't find anything in Qt that would seem to control it, so this issue can likely be closed as a non-started.

**Comment by trisyoungs** [comment]
Closing, since this appears to be desktop-dependent and out of our control.
