### ISSUE TITLE
Epic / Issue Management, August 2021

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#780]
### Focus
Clean up stale, irrelevant, and dangling issues.

### Apparently Completed, But Not Closed
- [x] #633
- [x] #607

### Stale / Redundant
- [x] #534
- [x] #528
- [x] #343
- [x] #244
- [x] #141
- [x] #136

### Out-of-Scope / Not Implementing
- [x] #445
- [x] #663
- [x] #292
- [x] #228

**Comment by trisyoungs** [comment]
@rprospero - Doing a bit of housekeeping on our bucket of issues. Pinpointed a handful that can probably be closed, but if you could sanity check the list that would be great.

**Comment by trisyoungs** [comment]
(... and some `EpicBot` fixes along the way).

**Comment by trisyoungs** [comment]
And removal of `EpicBot` entirely, since GitHub have introduced Task Lists - https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists

**Comment by rprospero** [comment]
These issues are now closed.
