### ISSUE TITLE
Spaces in Module (and Configuration) Names

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#822]
**Describe the bug**
Spaces in module names are currently alllowed, which ultimately leads to restart files being written which don't correctly parse when loading, since the data tags are unquoted.

For example, given the module name `Name With Spaces`, processing data entries in the restart file would begin like this:
```
Processing Name With Spaces//FullWeights  NeutronWeights  1 1
```
...whereas this would need to be wrriten as:
```
Processing "Name With Spaces//FullWeights"  NeutronWeights  1 1
```

Disallowing names with spaces would solve these issues, and probably isn't too bad an idea anyway. `Configuration`s are already referred to by their "niceName()" which replaces spaces with underscores - this could be enforced at run time, with no conversions made instead, and the `niceName()` (and `Module::uniqueName()`?) functions removed in favour of plain old `name()`.

**Comment by rprospero** [comment]
At the TSC meeting, we discussed that the issue with spaces in names is ultimately a parsing issue.  With issue #832 and an upcoming ticket to replace the input file with an existing file format, the parsing questions will be handled for us.  This also allows the name to always be the same in the input file and in the GUI, which will be less confusing to the users.
