### ISSUE TITLE
Deleting of individual layers in GUI results in multiplying the layer which should be deleted

### ISSUE THREAD

**Issue by johannabusch** [disorderedmaterials/dissolve#839]
**Describe the bug**
When trying to delete a layer in the GUI, the same layer is added another time instead of deleting it.
The version of dissolve is 0.8.5

![image](https://user-images.githubusercontent.com/56266543/140281730-b747fded-d9e7-428a-90f9-2aa2bf33eecf.png)

**Operating System:**
 - OS: Linux  (delete as appropriate)
 - OS version / flavour: Ubuntu 20.04

**Comment by trisyoungs** [comment]
Tab management appears to be broken in `0.8.5`. Related to #830.
