### ISSUE TITLE
Display of the axis for R-factors in the GUI is in the wrong dimension

### ISSUE THREAD

**Issue by johannabusch** [disorderedmaterials/dissolve#843]
The display of the axis for R-factors in the GUI is in the wrong dimension.
![image](https://user-images.githubusercontent.com/56266543/140468048-3bff70ff-964f-4182-8bc8-0b7d91d15117.png)

Dissolve Version 0.8.5, Linux

**Comment by trisyoungs** [comment]
This is a related to an issue with the vertical shifting of datasets persisting from previously-displayed data.  As a workaround, cycling the shift amount with the `S` keyboard shortcut on the graph should reset things back to normal.
