### ISSUE TITLE
Bond colouring in ball-and-stick views is reversed

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#858]
**Describe the bug**
Species models viewed in ball-and-stick mode show the bond-half colours switched w.r.t. to the colours of the involved atoms.

**Comment by rprospero** [comment]
Is this still the case?  In the screen shot below, the red atom has a red stick coming out of it.

![20211130_14h04m02s_grim](https://user-images.githubusercontent.com/1728853/144061577-76455e22-d5ae-4691-b7de-da19c4b7fa0c.png)

**Comment by trisyoungs** [comment]
Hmmm. I don't seem to see this problem anymore either, so to be honest I'm not sure where it came from (or where it went!). I guess we can close for now, and reopen if we stumble across an input file which displays the behaviour.

**Comment by trisyoungs** [comment]
In fact this *does* occur when drawing bonds in the species editor (but this is not the place I originally noticed it).

**Comment by trisyoungs** [comment]
Reopening as this still occurs in the `SpeciesViewer` for periodic models.
