### ISSUE TITLE
Control Layer

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#88]
An (optional) Control Layer can manage the execution of processing layers, enabling regeneration of configurations, minimisation, refinement, testing, fitting of parameters, rather than just running through them one-by-one. With Procedure definitions for configuration creation, this could be the best route to allow searching through this type of parameter space. Can dump a restart file at each 'good' or 'best' point, rather than every 'n' iterations of the main loop.

Control Layer could be present all the time, but hidden, with the default option being just to continually iterate over the layers.

**Comment by jws-1** [comment]
Closing as superseded by #1652.
