### ISSUE TITLE
Add forcefield wizard needs updating

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#884]
**Describe the bug**
The Add Forcefield wizard relies on the messages output to show errors for missing parameters etc. - since the messages are now in their own separate tab, there is no visible feedback to the user when missing parameters are encountered.

Errors / missing parameters lists should be redirected to the wizard itself.

**Comment by rprospero** [comment]
![20220210_15h10m11s_grim](https://user-images.githubusercontent.com/1728853/153436577-5ab3de57-338e-4c4a-a5c7-93148d7677db.png)

@trisyoungs  Would this error message be sufficient?

**Comment by trisyoungs** [comment]
@rprospero Change "forcefields" for "atom types" and I think that will do it!

**Comment by rprospero** [comment]
Fixed in PR #971
