### ISSUE TITLE
Standard file format for input file

### ISSUE THREAD

**Issue by rprospero** [disorderedmaterials/dissolve#899]
The input file is currently a bespoke file format that requires a custom parser.  Using an existing file format (e.g. JSON, TOML) would eliminate a large amount of boilerplate code from our maintanence burden.  Additionally, it would allow users to tap into an existing tooling eco-system for creating, inspecting, and modifying the input files.

Whatever format is chosen for the input file should be the same format as chosen for the restart file in #832

**Comment by IVlaD17** [comment]
List of file formats to look at:
- [ ] XML
- [ ] XAML
- [ ] JSON
- [ ] YAML
- [ ] TOML

**Comment by rprospero** [comment]
Just as a lark, we could look at [Dhall](https://dhall-lang.org).  It does have some advantages compared to the other formats and it can be trivially converted down to any of the other formats.  On the other hand, I can't imagine that it has good library support.

**Comment by IVlaD17** [comment]
Ideally, we'd like to not have to add another dependency in the shape of a parser, but if we have to, we should aim to get something widely used, well-supported and robust.

**Comment by IVlaD17** [comment]
# JSON
## Library Support
## Hand Editing
## Tooling Support
## Future Proofing
## Performance

**Comment by IVlaD17** [comment]
# YAML
## Library Support
## Hand Editing
## Tooling Support
## Future Proofing
## Performance

**Comment by rprospero** [comment]
The following system test files can be run while only parsing the `Species`, `Master`, and `PairPotential` blocks:

- `tests/input/benzene.txt`
- `tests/input/py5-ntf2.txt`
- `tests/input/water.txt`
