### ISSUE TITLE
Timing is inaccurate if module legitimately doesn't run

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#917]
**Describe the bug**
Some modules (e.g. `MD`) can have a successful processing stage which performs no work (e.g. because some data has not changed, or if energy is not stable etc.).  This pollutes the true timing of the module.

**Comment by trisyoungs** [comment]
May need to evolve the return type of `Module::process()` to an enum in order to capture potential `NotRun` states.

**Comment by rhinoella** [comment]
Resolved by PR #1539

**Comment by rhinoella** [comment]
Resolved by PR #1539
