### ISSUE TITLE
Remove MinimiserBase<T>

### ISSUE THREAD

**Issue by trisyoungs** [disorderedmaterials/dissolve#947]
**Describe the feature / issue**
Minimisation algorithms (Monte Carlo, praxis etc.) are all built on a template class (`MinimiserBase`) which has a historically bad and unnecessary design.

Proposal is to remove the use of `MinimiserBase` completely and move to independent classes specific to each minimisation algorithm, and replace the use of cost function callbacks with lambdas.

**Comment by rprospero** [comment]
Closed in #976
